services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: job_search_platform
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  # Change the host port to 3307
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
